on: [push]
name: Release
jobs:
  release:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
            ~/Library/Caches/go-build # Build cache (Mac)
            '%LocalAppData%\go-build' # Build cache (Windows)
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build -ldflags "-s -w"
      - name: Debug
        run: ls
      - name: Compress windows binary
        if: startsWith(matrix.os, 'windows')
        uses: svenstaro/upx-action@v2
        with:
          file: furbnicator.exe
      - name: Compress other binary
        if: ! startsWith(matrix.os, 'windows')
        uses: svenstaro/upx-action@v2
        with:
          file: furbnicator
      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: furbnicator_${{ matrix.os }}
          path: furbnicator*
